// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCpyy2fEh5slwBcibrnarg10e65KFH2e7w',
    appId: '1:354468692774:web:7da7549cb1d26c255277e7',
    messagingSenderId: '354468692774',
    projectId: 'vyapaar-connect-dfae0',
    authDomain: 'vyapaar-connect-dfae0.firebaseapp.com',
    storageBucket: 'vyapaar-connect-dfae0.firebasestorage.app',
    measurementId: 'G-WYM8Z937YW',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDhqsvdyvnzYqxLoUSIKbsJOY-9KkZg4I8',
    appId: '1:354468692774:android:0ddacaea4115359e5277e7',
    messagingSenderId: '354468692774',
    projectId: 'vyapaar-connect-dfae0',
    storageBucket: 'vyapaar-connect-dfae0.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCe0V57JdmSn5s1l2jC5FaeHhjE-o69zNE',
    appId: '1:354468692774:ios:2427b71fd87da9235277e7',
    messagingSenderId: '354468692774',
    projectId: 'vyapaar-connect-dfae0',
    storageBucket: 'vyapaar-connect-dfae0.firebasestorage.app',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCe0V57JdmSn5s1l2jC5FaeHhjE-o69zNE',
    appId: '1:354468692774:ios:2427b71fd87da9235277e7',
    messagingSenderId: '354468692774',
    projectId: 'vyapaar-connect-dfae0',
    storageBucket: 'vyapaar-connect-dfae0.firebasestorage.app',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCpyy2fEh5slwBcibrnarg10e65KFH2e7w',
    appId: '1:354468692774:web:74b5540e8dc464d45277e7',
    messagingSenderId: '354468692774',
    projectId: 'vyapaar-connect-dfae0',
    authDomain: 'vyapaar-connect-dfae0.firebaseapp.com',
    storageBucket: 'vyapaar-connect-dfae0.firebasestorage.app',
    measurementId: 'G-78JRM4T1JJ',
  );
}
